version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@daaku/qunit-puppeteer"
    versions:
    - 0.3.0
  - dependency-name: esbuild
    versions:
    - 0.9.0
